### ISSUE TITLE
一个疑似笔误

### ISSUE THREAD

**Issue by yebuzhen** [Snailclimb/springboot-guide#20]
[示例2: @Controller+@ResponseBody 返回 JSON 格式数据](https://snailclimb.gitee.io/springboot-guide/#/./docs/basis/RestControllerVSController?id=%e7%a4%ba%e4%be%8b2-controllerresponsebody-%e8%bf%94%e5%9b%9e-json-%e6%a0%bc%e5%bc%8f%e6%95%b0%e6%8d%ae)

一个小问题: 这里的Person类应该放在entity包下, 而不是controller包下吧? 谢谢!
![image](https://user-images.githubusercontent.com/23526324/87147388-21df4f80-c2df-11ea-8644-42c596a25567.png)

**Comment by Snailclimb** [comment]
> [示例2: @Controller+@ResponseBody 返回 JSON 格式数据](https://snailclimb.gitee.io/springboot-guide/#/./docs/basis/RestControllerVSController?id=%e7%a4%ba%e4%be%8b2-controllerresponsebody-%e8%bf%94%e5%9b%9e-json-%e6%a0%bc%e5%bc%8f%e6%95%b0%e6%8d%ae)
> 
> 一个小问题: 这里的Person类应该放在entity包下, 而不是controller包下吧? 谢谢!
> ![image](https://user-images.githubusercontent.com/23526324/87147388-21df4f80-c2df-11ea-8644-42c596a25567.png)

项目中是放在实体类包下，这里只是为了演示哈。
